# Generated by Django 5.2.11 on 2026-02-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Termino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "palabra",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Palabra Base"
                    ),
                ),
                (
                    "definicion",
                    models.TextField(blank=True, verbose_name="Definición General"),
                ),
                (
                    "categoria_gramatical",
                    models.CharField(
                        choices=[
                            ("sustantivo", "Sustantivo"),
                            ("verbo", "Verbo"),
                            ("adjetivo", "Adjetivo"),
                        ],
                        default="sustantivo",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Término",
                "verbose_name_plural": "Términos",
            },
        ),
        migrations.CreateModel(
            name="Variante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "palabra_variante",
                    models.CharField(max_length=100, verbose_name="Variante"),
                ),
                ("pais", models.CharField(max_length=50, verbose_name="País/Región")),
                (
                    "explicacion",
                    models.TextField(blank=True, verbose_name="Contexto de uso"),
                ),
                (
                    "frecuencia_uso",
                    models.IntegerField(
                        default=1, help_text="Escala de popularidad (1-10)"
                    ),
                ),
                (
                    "termino_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="core.termino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante Léxica",
                "verbose_name_plural": "Variantes Léxicas",
            },
        ),
    ]
