# Generated by Django 5.2.11 on 2026-09-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termino',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Término', 'verbose_name_plural': 'Términos'},
        ),
        migrations.AddField(
            model_name='termino',
            name='acepciones',
            field=models.JSONField(blank=True, default=list, help_text='Lista de significados alternativos', verbose_name='Acepciones'),
        ),
        migrations.AddField(
            model_name='termino',
            name='antonimos',
            field=models.JSONField(blank=True, default=list, verbose_name='Antónimos'),
        ),
        migrations.AddField(
            model_name='termino',
            name='categoria_semantica',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoría semántica'),
        ),
        migrations.AddField(
            model_name='termino',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AddField(
            model_name='termino',
            name='ejemplo',
            field=models.TextField(blank=True, verbose_name='Ejemplo de uso'),
        ),
        migrations.AddField(
            model_name='termino',
            name='etimologia',
            field=models.TextField(blank=True, verbose_name='Etimología'),
        ),
        migrations.AddField(
            model_name='termino',
            name='familia_lexica',
            field=models.JSONField(blank=True, default=list, verbose_name='Familia léxica'),
        ),
        migrations.AddField(
            model_name='termino',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('muy alta', 'Muy alta'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('muy baja', 'Muy baja')], max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='termino',
            name='locuciones',
            field=models.JSONField(blank=True, default=list, verbose_name='Locuciones'),
        ),
        migrations.AddField(
            model_name='termino',
            name='marcas',
            field=models.JSONField(blank=True, default=list, verbose_name='Marcas de uso'),
        ),
        migrations.AddField(
            model_name='termino',
            name='nivel',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('coloquial', 'Coloquial'), ('culto', 'Culto'), ('tecnico', 'Técnico'), ('literario', 'Literario'), ('juvenil', 'Juvenil')], max_length=20, verbose_name='Nivel de uso'),
        ),
        migrations.AddField(
            model_name='termino',
            name='sinonimos',
            field=models.JSONField(blank=True, default=list, verbose_name='Sinónimos'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='categoria_gramatical',
            field=models.CharField(choices=[('sustantivo', 'Sustantivo'), ('verbo', 'Verbo'), ('adjetivo', 'Adjetivo'), ('adverbio', 'Adverbio'), ('pronombre', 'Pronombre'), ('preposicion', 'Preposición'), ('conjuncion', 'Conjunción'), ('interjeccion', 'Interjección'), ('articulo', 'Artículo')], default='sustantivo', max_length=20),
        ),
    ]
