# Generated by Django 5.2.11 on 2026-09-16 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre_nativo', models.CharField(max_length=100)),
                ('nombre_ingles', models.CharField(max_length=100)),
                ('familia', models.CharField(blank=True, max_length=50)),
                ('hablantes_millones', models.IntegerField(default=0)),
                ('direccion', models.CharField(choices=[('ltr', 'Izquierda a derecha'), ('rtl', 'Derecha a izquierda')], default='ltr', max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['-hablantes_millones'],
            },
        ),
        migrations.AlterModelOptions(
            name='termino',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Termino', 'verbose_name_plural': 'Terminos'},
        ),
        migrations.AlterModelOptions(
            name='variante',
            options={'verbose_name': 'Variante Lexica', 'verbose_name_plural': 'Variantes Lexicas'},
        ),
        migrations.AlterField(
            model_name='termino',
            name='acepciones',
            field=models.JSONField(blank=True, default=list, verbose_name='Acepciones'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='antonimos',
            field=models.JSONField(blank=True, default=list, verbose_name='Antonimos'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='categoria_gramatical',
            field=models.CharField(choices=[('sustantivo', 'Sustantivo'), ('verbo', 'Verbo'), ('adjetivo', 'Adjetivo'), ('adverbio', 'Adverbio'), ('pronombre', 'Pronombre'), ('preposicion', 'Preposicion'), ('conjuncion', 'Conjuncion'), ('interjeccion', 'Interjeccion'), ('articulo', 'Articulo')], default='sustantivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='termino',
            name='categoria_semantica',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoria semantica'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='definicion',
            field=models.TextField(blank=True, verbose_name='Definicion General'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='etimologia',
            field=models.TextField(blank=True, verbose_name='Etimologia'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='familia_lexica',
            field=models.JSONField(blank=True, default=list, verbose_name='Familia lexica'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='nivel',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('coloquial', 'Coloquial'), ('culto', 'Culto'), ('tecnico', 'Tecnico'), ('literario', 'Literario'), ('juvenil', 'Juvenil')], max_length=20, verbose_name='Nivel de uso'),
        ),
        migrations.AlterField(
            model_name='termino',
            name='sinonimos',
            field=models.JSONField(blank=True, default=list, verbose_name='Sinonimos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='variante',
            name='frecuencia_uso',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variante',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='Pais/Region'),
        ),
        migrations.CreateModel(
            name='TraduccionTermino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traduccion', models.CharField(max_length=200)),
                ('definicion_nativa', models.TextField(blank=True)),
                ('ejemplo_nativo', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('nivel_correspondencia', models.CharField(choices=[('exacta', 'Traduccion exacta'), ('parcial', 'Parcial'), ('aproximada', 'Aproximada'), ('cultural', 'Equivalente cultural')], default='exacta', max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('votos', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traducciones_aportadas', to=settings.AUTH_USER_MODEL)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='core.idioma')),
                ('termino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='core.termino')),
            ],
            options={
                'verbose_name': 'Traduccion de termino',
                'verbose_name_plural': 'Traducciones de terminos',
                'ordering': ['-votos'],
                'unique_together': {('termino', 'idioma')},
            },
        ),
    ]
