# Generated by Django 5.2.11 on 2026-09-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_termino_options_termino_acepciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='', max_length=10)),
                ('categoria_semantica', models.CharField(db_index=True, max_length=50)),
                ('nivel', models.CharField(choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('xp_total', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['categoria_semantica', 'nivel'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subclase', models.CharField(choices=[('intro', 'Introduccion'), ('practica', 'Practica'), ('evaluacion', 'Evaluacion')], default='intro', max_length=20)),
                ('orden', models.IntegerField(default=1)),
                ('teoria', models.TextField(blank=True)),
                ('xp_reward', models.IntegerField(default=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.curso')),
            ],
            options={
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('pregunta', models.TextField()),
                ('opcion_a', models.CharField(max_length=200)),
                ('opcion_b', models.CharField(max_length=200)),
                ('opcion_c', models.CharField(blank=True, max_length=200)),
                ('opcion_d', models.CharField(blank=True, max_length=200)),
                ('respuesta_correcta', models.CharField(default='A', max_length=1)),
                ('explicacion', models.TextField(blank=True)),
                ('xp_reward', models.IntegerField(default=10)),
                ('termino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.termino')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='cursos.leccion')),
            ],
            options={
                'ordering': ['leccion', 'orden'],
            },
        ),
    ]
